sudo: required
dist: trusty
language: cpp
matrix:
include:
  - compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:  COMPILER=g++-5

before_install:
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/cppcheck       $TRAVIS_BUILD_DIR/docs/reports/gcov        $TRAVIS_BUILD_DIR/docs/reports/gtest
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/make           $TRAVIS_BUILD_DIR/docs/reports/oclint      $TRAVIS_BUILD_DIR/docs/reports/rats
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/reports/valgrind       $TRAVIS_BUILD_DIR/docs/reports/vera++      $TRAVIS_BUILD_DIR/docs/reports/lcov
  - mkdir -p      $TRAVIS_BUILD_DIR/docs/html                   $TRAVIS_BUILD_DIR/3rdparty                 $TRAVIS_BUILD_DIR/build
  - pip install --user cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov gcovr curl unzip valgrind rats cppcheck vera++ uuid-dev
  - git submodule init
  - git submodule update
  - cd $TRAVIS_BUILD_DIR/3rdparty
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
  - unzip sonar-scanner-2.6.1.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/sonar-scanner-2.6.1/bin:$PWD/build-wrapper-linux-x86:$PATH
script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -DXTD_BUILD_TESTS:BOOLEAN=ON -DXTD_BUILD_EXAMPLES:BOOLEAN=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DXTD_CI_BUILD=TRUE .. 2>&1 | tee ../docs/reports/make/cmake.log
  - build-wrapper-linux-x86-64 --out-dir . make clean all unit_tests examples
  - $TRAVIS_BUILD_DIR/build/tests/unit_tests --xml:$TRAVIS_BUILD_DIR/docs/reports/gtest
  - cd $TRAVIS_BUILD_DIR/
  - valgrind --tool=memcheck -v --trace-children=yes --xml=yes --xml-file=docs/reports/valgrind/unit_tests.memcheck.xml $TRAVIS_BUILD_DIR/build/tests/unit_tests
  - for item in $(find build_config -type f); do vera++ -x docs/reports/vera++/$(basename $item).xml $item > /dev/null; done
  - for item in $(find include -type f); do vera++ -x docs/reports/vera++/$(basename $item).xml $item > /dev/null; done
  - for item in $(find include -name *.hpp); do cppcheck --inline-suppr --suppressions-list=assets/cppcheck-suppressions.txt --std=c++11 --platform=unix64 --enable=all --xml-version=2 $item 2> docs/reports/cppcheck/$(basename $item).xml; done
  - for item in $(find build_config -name *.cpp); do cppcheck --inline-suppr --suppressions-list=assets/cppcheck-suppressions.txt --std=c++11 --platform=unix64 --enable=all --xml-version=2 $item 2> docs/reports/cppcheck/$(basename $item).xml; done
  - rats --xml -w 3 build_config include > docs/reports/rats/rats.xml
  - cd $TRAVIS_BUILD_DIR/build/tests
  - if [ -e "$(ls *.xml)" ]; then cp *.xml $TRAVIS_BUILD_DIR/docs/reports/gtest; fi
  - for item in $( find -name '*.gcda' ); do gcov -l $item; done
  - for item in $( find -name '*.gcda' ); do gcovr -x -r .  > $TRAVIS_BUILD_DIR/docs/reports/gcov/$(basename $item).xml; done
  - cd $TRAVIS_BUILD_DIR/
  - cp assets/sonar* .
  - sonar-scanner -e -X -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.github.oauth=$SONAR_GITHUB_TOKEN
success:
  - cd $TRAVIS_BUILD_DIR/docs/html
  - git init
  - git remote add docs git@github.com:djmott/xtd-docs.git
  - git pull
  - cd $TRAVIS_BUILD_DIR/build
  - make docs
  - cd $TRAVIS_BUILD_DIR/docs/html
  - git commit -am "travis-ci documentation update"
  - git push docs master
after_success:
  - coveralls
