XTL: Text parsing and AST generation library
Text parsing and AST generation library
Namespaces
xtd::parse
Text parsing and AST generation.
Data Structures
class xtd::parse::and_<... >
Represents a parse algorithm where all specified elements parse are contiguously present in the input stream All the terminals and rules listed in the parameter pack must parse successfully to satisfy the parse rule.
class xtd::parse::character< _value >
Character terminal parsing algorithm.
class xtd::parse::one_or_more_< _Ty >
Represents a parse algorithm where where the terminal or rule is repeated one or more times in the input stream The specified item must parse successfully at least once to satisfy the parse rule.
class xtd::parse::or_<... >
Represents a parse algorithm where one of the listed elements is present in the input stream One of the terminals or rules listed in the parameter pack must parse successfully to satisfy the parse rule.
class xtd::parser< _RuleT, _IgnoreCase, _WhitespaceT >
class xtd::parse::regex< _Ty, >
regular expression parsing algorithm.
class xtd::parse::rule< _DeclT, _ImplT >
Curiously recurring template pattern to simplify creation of rule_base implementations Rules and terminals implement the rule_base interface through this pattern.
class xtd::parse::rule_base
Base class of both rules and terminals Though rules and terminals are technically different they share the rule_base ancestor in XTL to have a cleaner object model and simpler parsing algorithms.
class xtd::parse::string< _Ty, >
String terminal parsing algorithm.
class xtd::parse::whitespace< _Ch >
list of whitespace characters to ignore in the input stream.
class xtd::parse::zero_or_more_< _Ty >
Represents a parse algorithm where the terminal or rule repeats zero or more times in the input stream Always successfully parses whether or not the element parses.
class xtd::parse::zero_or_one_< _Ty >
Represents a parse algorithm where the terminal or rule repeats exactly zero or one time in the input stream Always successfully parses whether or not the element parses.
Macros
#define CHARACTER_(_name, _value)
Declares a single character terminal.
#define REGEX(_name, _value)
Declares a regular expression terminal.
#define STRING(_name, _value)
Declares a string terminal Must be used at namespace scope.
#define STRING_(x)
Declares a string terminal with the value equal to the name.
Typedefs
using xtd::parse::one_or_more_< _Ty >::_super_t = rule< one_or_more_< _Ty >>
using xtd::parse::zero_or_more_< _Ty >::_super_t = rule< zero_or_more_< _Ty >>
using xtd::parse::zero_or_one_< _Ty >::_super_t = rule< zero_or_one_< _Ty >>
using xtd::parse::rule< _DeclT, _ImplT >::decl_type = _DeclT
using xtd::parse::rule< _DeclT, _ImplT >::impl_type = _ImplT
using xtd::parse::rule_base::pointer_type = std::shared_ptr< rule_base >
using xtd::parse::rule< _DeclT, _ImplT >::rule_type = rule< _DeclT, _ImplT >
using xtd::parse::rule_base::vector_type = std::vector< pointer_type >
using xtd::parse::whitespace< _Ch >::whitespace_type = whitespace< _Ch... >
Functions
template<typename... _ChildRuleTs>
xtd::parse::one_or_more_< _Ty >::one_or_more_ (_ChildRuleTs &&...oChildRules)
template<typename... _ChildRuleTs>
xtd::parse::rule< _DeclT, _ImplT >::rule (_ChildRuleTs &&...oChildRules)
template<typename... _ChildRuleTs>
xtd::parse::rule_base::rule_base (_ChildRuleTs &&...oChildRules)
Constructor.
template<typename... _ChildRuleTs>
xtd::parse::zero_or_more_< _Ty >::zero_or_more_ (_ChildRuleTs &&...oChildRules)
template<typename... _ChildRuleTs>
xtd::parse::zero_or_one_< _Ty >::zero_or_one_ (_ChildRuleTs &&...oChildRules)
virtual bool xtd::parse::rule_base::isa (const std::type_info &oType) const =0
Determines if the interface is implemented by a concrete type.
virtual bool xtd::parse::rule< _DeclT, _ImplT >::isa (const std::type_info &oType) const override
Determines if the interface is implemented by a concrete type.
const vector_type & xtd::parse::rule_base::items () const
Accessor for child parse elements.
template<typename _IteratorT >
static parse::rule_base::pointer_type xtd::parser< _RuleT, _IgnoreCase, _WhitespaceT >::parse (_IteratorT begin, _IteratorT end)
virtual const std::type_info & xtd::parse::rule_base::type () const =0
Gets the type info of the concrete implementation.
virtual const std::type_info & xtd::parse::rule< _DeclT, _ImplT >::type () const override
Gets the type info of the concrete implementation.
Variables
vector_type xtd::parse::rule_base::_Items
Detailed Description
Data Structure Documentation
class xtd::parse::and_
template<typename...>
class xtd::parse::and_<... >
Represents a parse algorithm where all specified elements parse are contiguously present in the input stream All the terminals and rules listed in the parameter pack must parse successfully to satisfy the parse rule.
Template Parameters
... list of child rules and terminals to parse
Definition at line 125 of file parse.hpp.
class xtd::parse::or_
template<typename...>
class xtd::parse::or_<... >
Represents a parse algorithm where one of the listed elements is present in the input stream One of the terminals or rules listed in the parameter pack must parse successfully to satisfy the parse rule.
Template Parameters
... list of child rules and terminals to parse
Definition at line 147 of file parse.hpp.
class xtd::parse::regex
template<typename _Ty, _Ty &>
class xtd::parse::regex< _Ty, >
regular expression parsing algorithm.
This template is infrequently used directly. The REGEX macro is provided to declare a regular expression terminal.
Definition at line 237 of file parse.hpp.
class xtd::parse::string
template<typename _Ty, _Ty &>
class xtd::parse::string< _Ty, >
String terminal parsing algorithm.
This template is infrequently used directly. The STRING and STRING_ macros are provided to declare string terminals.
Definition at line 218 of file parse.hpp.
class xtd::parse::whitespace
template<char... _Ch>
class xtd::parse::whitespace< _Ch >
list of whitespace characters to ignore in the input stream.
Whitespace characters are parsed and discarded from the input stream when encountered between rules or terminals. A typical whitespace declaration for written language might be: whitespace<'', '
', '', ' '>;
Template Parameters
_Ch... list of characters to ignore.
Definition at line 209 of file parse.hpp.
Data Fields
whitespace_type
Macro Definition Documentation
#define CHARACTER_ (_name, _value)
#include <parse.hpp>
Value:
namespace _{} \
  using _name = xtd::parse::character<_value>
Declares a single character terminal.
Must be used at namespace scope.
Parameters
_name name of the terminal.
_value value of the terminal. Must be a single character enclosed in single quotes.
Definition at line 41 of file parse.hpp.
#define REGEX (_name, _value)
#include <parse.hpp>
Value:
namespace _{ char _name[] = _value; } \
      using _name = xtd::parse::regex< decltype(_::_name), _::_name>;
Declares a regular expression terminal.
Must be used at namespace scope.
Parameters
_name name of the terminal.
_value regular expression of the terminal.
Definition at line 52 of file parse.hpp.
#define STRING (_name, _value)
#include <parse.hpp>
Value:
namespace _{ char _name[] = _value; } \
      using _name = xtd::parse::string< decltype(_::_name), _::_name>;
Declares a string terminal Must be used at namespace scope.
Parameters
_name name of the terminal
_value string value of the terminal. Must be enclosed in double quotes.
Definition at line 29 of file parse.hpp.
#define STRING_ (x)
#include <parse.hpp>
Value:
namespace _{ char x[] = #x; } \
      using x = xtd::parse::string< decltype(_::x), _::x>;
Declares a string terminal with the value equal to the name.
Must be used at namespace scope
Parameters
x name and value of the terminal
Definition at line 19 of file parse.hpp.
Typedef Documentation
template<char... _Ch> using xtd::parse::whitespace< _Ch >::whitespace_type = whitespace<_Ch...>
Definition at line 211 of file parse.hpp.
Function Documentation
template<typename... _ChildRuleTs> xtd::parse::rule_base::rule_base (_ChildRuleTs &&... oChildRules) inline explicit
#include <parse.hpp>
Constructor.
Parameters
[in] _ChildRuleTs list of child rules that successfully parsed to satisfy the current parse rule. The child rules are stored in a local variable and accessible via the items() member.
Definition at line 70 of file parse.hpp.
References xtd::parse::rule_base::isa(), and xtd::parse::rule_base::type().
Referenced by xtd::parse::rule< zero_or_one_< _Ty > >::isa().
virtual bool xtd::parse::rule_base::isa (const std::type_info & oType) const pure virtual
#include <parse.hpp>
Determines if the interface is implemented by a concrete type.
Parameters
[in] oType type to test
Returns
true if the implementation's is the specified type
Implemented in xtd::parse::rule< _DeclT, _ImplT >, xtd::parse::rule< zero_or_more_< _Ty > >, xtd::parse::rule< one_or_more_< _Ty > >, xtd::parse::rule< character< _value > >, and xtd::parse::rule< zero_or_one_< _Ty > >.
Referenced by xtd::parse::rule_base::rule_base().
template<typename _DeclT, typename _ImplT = _DeclT> virtual bool xtd::parse::rule< _DeclT, _ImplT >::isa (const std::type_info & oType) const inline override virtual
#include <parse.hpp>
Determines if the interface is implemented by a concrete type.
Parameters
[in] oType type to test
Returns
true if the implementation's is the specified type
Implements xtd::parse::rule_base.
Definition at line 110 of file parse.hpp.
const vector_type& xtd::parse::rule_base::items () const inline
#include <parse.hpp>
Accessor for child parse elements.
Returns
a vector of the parsed child rules and terminals
Definition at line 83 of file parse.hpp.